substitutions:
  # Default values
  _ARTIFACT_NAME: 'data-loader'
  _PROJECT: another-data-platform

steps:

  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'eu.gcr.io/${_PROJECT}/run/${_ARTIFACT_NAME}:$SHORT_SHA', '.']

  - name: gcr.io/cloud-builders/docker
    args: ['push', 'eu.gcr.io/${_PROJECT}/run/${_ARTIFACT_NAME}:$SHORT_SHA']
